---
title: "Generics Analyses"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load libraries
```{r load_libraries, message = F, warning = F}
library(tidyverse)
library(lubridate)
library(lme4)
library(DT)
library(ggpirate)

theme_set(theme_classic(base_size = 14))
```

read in data
```{r, message = F}
data <- read_csv("data/anonymized_data.csv")
```

filter out participants who didn't get attention check right
```{r}
qualtrics_filtered <- data %>%
  filter(Q10 == "kobas,feps,dands")
```

Munge data
```{r}
high_words <- c("dog","truck","pizza")
med_words <- c("pie", "stone", "goat")
low_words <- c("vegetable", "bike", "squirrel")

q1 <- qualtrics_filtered %>%
  select(id, Q2_1, baseline_1, feature_initial) %>%
  mutate(question = 1) %>%
  rename(baseline = baseline_1, feature = feature_initial, response = Q2_1)

q2 <- qualtrics_filtered %>%
  select(id, Q5_1, baseline_2, feature_2) %>%
  mutate(question = 1) %>%
  rename(baseline = baseline_2, feature = feature_2, response = Q5_1)

q3 <- qualtrics_filtered %>%
  select(id, Q6_1, baseline_3, feature_3) %>%
  mutate(question = 1) %>%
  rename(baseline = baseline_3, feature = feature_3, response = Q6_1)

response_data <- bind_rows(q1, q2, q3) %>%
  mutate(type = if_else(baseline %in% high_words, "high",
                        if_else(baseline %in% med_words, "medium",
                                "low"))) %>%
  mutate(type = factor(type, levels = c("low", "medium", "high")))
```

Exploratory data analysis
```{r}

response_data %>%
  group_by(feature, type) %>%
  summarise(respose = mean(response)) %>%
  datatable()

ggplot(response_data, aes(x = type, y = response)) + 
  facet_wrap(~ feature) +
  #geom_violin() +
  #geom_jitter(width = .1)
  geom_pirate()
```

fit model
```{r}

lm <- lmer(response ~ type + feature + (1|id), data = response_data)
summary(lm)
```

plot model predictions
```{r}
predicted_data <- response_data %>%
  mutate(predicted = predict(lm)) %>%
  gather(measure, value, response, predicted)

ggplot(predicted_data, aes(x = type, y = value, color = measure)) + 
  facet_wrap(~ feature) +
  geom_violin() +
  geom_jitter(width = .1)
```

plot model predictions with the jitter and violin plots paired
```{r}
predicted_data <- response_data %>%
  mutate(predicted = predict(lm)) %>%
  gather(measure, value, response, predicted)

ggplot(predicted_data, aes(x = type , y = value, color = measure,fill = measure))  + 
      facet_wrap(~ feature) + 
      geom_violin(fill="white", position = position_dodge(width=1)) +
      geom_point(position = position_jitterdodge(jitter.width = 0.25, dodge.width=0.9), size = 0.7)
      
```
